package at.asdf00.avaplus;

import at.asdf00.avaplus.util.CustomConfig;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.io.File;

public class ModConfig {
    public static CustomConfig conf;

    public static long AMOGUS_RFTOREPLICATE = 40_000_000_000L;
    public static long AMOGUST2_RFTOREPLICATE = 32_768_000_000_000L;
    public static long SAURON_YIELD_ICATALYST = 750_000_000_000_000L;
    public static long SAURON_YIELD_IINGOT = 12_000_000_000_000_000L;
    public static long SAURON_YIELD_IBLOCK = 120_000_000_000_000_000L;

    public static void init(File file) {
        conf = new CustomConfig(file);
        String category;

        category = "singularity_replicator";
        conf.addCustomCategoryComment(category, "Configure the replicator");
        AMOGUS_RFTOREPLICATE = conf.getLong("RF_TO_REPLICATE", category, 40_000_000_000L, 1, Long.MAX_VALUE, "Set the energy needed to replicate a singularity");

        category = "replicator_tier2";
        conf.addCustomCategoryComment(category, "Configure the replicator tier 2");
        AMOGUST2_RFTOREPLICATE = conf.getLong("RF_TO_REPLICATE_T2", category, 32_768_000_000_000L, 1, Long.MAX_VALUE, "Set the energy needed to replicate any item");

        category = "black_hole_generator";
        conf.addCustomCategoryComment(category, "Set the energy yield for specific items");
        SAURON_YIELD_ICATALYST = conf.getLong("RF_YIELD_ICATALYST", category, 750_000_000_000_000L, 1, Long.MAX_VALUE, "Set the energy generated by consuming an infinity catalyst");
        SAURON_YIELD_IINGOT = conf.getLong("RF_YIELD_IINGOT", category, 12_000_000_000_000_000L, 1, Long.MAX_VALUE, "Set the energy generated by consuming an infinity ingot");
        SAURON_YIELD_IBLOCK = conf.getLong("RF_YIELD_IBLOCK", category, 120_000_000_000_000_000L, 1, Long.MAX_VALUE, "Set the energy generated by consuming an infinity block");

    }
    public static void registerConfig(FMLPreInitializationEvent e) {
        Main.configFile = new File(e.getModConfigurationDirectory() + "/" + References.MODID);
        Main.configFile.mkdirs();
        init(new File(Main.configFile.getPath(), References.MODID + ".cfg"));
    }
}
