package at.asdf00.avaplus;

import at.asdf00.avaplus.util.CustomConfig;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.io.File;

public class ModConfig {
    public static CustomConfig conf;

    public static long AMOGUS_RFTOREPLICATE = 40_000_000_000L; // 40GRF
    public static long AMOGUST2_RFTOREPLICATE = 32_768_000_000_000L; // 32TRF
    public static int SAURON_MATTER_CAPACITY = 4_266_624; // decrements 1 per tick, 1 matter = about 2.1GRF at full efficiency
    public static int SAURON_YIELD_ICATALYST = 333; // yields about 700GRF
    public static int SAURON_YIELD_IINGOT = 6_666; // yields about 14TRF
    public static int SAURON_YIELD_IBLOCK = 66_666; // yields about 140TRF

    public static void init(File file) {
        conf = new CustomConfig(file);
        String category;

        category = "singularity_replicator";
        conf.addCustomCategoryComment(category, "Configure the replicator");
        AMOGUS_RFTOREPLICATE = conf.getLong("RF_TO_REPLICATE", category, 40_000_000_000L, 1, Long.MAX_VALUE,
                "Set the energy needed to replicate a singularity");

        category = "replicator_tier2";
        conf.addCustomCategoryComment(category, "Configure the replicator tier 2");
        AMOGUST2_RFTOREPLICATE = conf.getLong("RF_TO_REPLICATE_T2", category, 32_768_000_000_000L, 1, Long.MAX_VALUE,
                "Set the energy needed to replicate any item");

        category = "black_hole_generator";
        conf.addCustomCategoryComment(category, "Set the parameters for the black hole generator");
        SAURON_MATTER_CAPACITY = conf.getInt("MATTER_CAPACITY", category, 4_266_624, 1, Integer.MAX_VALUE / 2,
                "Set the matter limit of the black hole generator (1 matter = max 2.1GRF)");
        SAURON_YIELD_ICATALYST = conf.getInt("YIELD_ICATALYST", category, 333, 1, Integer.MAX_VALUE / 2,
                "Set the matter generated by consuming an infinity catalyst");
        SAURON_YIELD_IINGOT = conf.getInt("YIELD_IINGOT", category, 6_666, 1, Integer.MAX_VALUE / 2,
                "Set the matter generated by consuming an infinity ingot");
        SAURON_YIELD_IBLOCK = conf.getInt("YIELD_IBLOCK", category, 66_666, 1, Integer.MAX_VALUE / 2,
                "Set the matter generated by consuming an infinity block");

    }
    public static void registerConfig(FMLPreInitializationEvent e) {
        Main.configFile = new File(e.getModConfigurationDirectory() + "/" + References.MODID);
        Main.configFile.mkdirs();
        init(new File(Main.configFile.getPath(), References.MODID + ".cfg"));
    }
}
